version: '3'
services:
  video-captcha:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./movies:/app/movies
    environment:
      NODE_ENV: development
